# Generated by Django 6.1 on 2026-09-07 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_materiais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('orientacao_uso', models.TextField(blank=True)),
                ('conceito_matematico', models.CharField(blank=True, max_length=150)),
                ('nivel', models.CharField(blank=True, max_length=100)),
                ('series', models.CharField(blank=True, max_length=150)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('quantidade_disponivel', models.PositiveIntegerField(default=1)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='materiais/')),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='cadastro_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=300)),
                ('apelido', models.CharField(blank=True, max_length=300)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('escola', models.CharField(max_length=150)),
                ('declaracao_escola', models.FileField(blank=True, null=True, upload_to='declaracoes/')),
                ('cidade_escola', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=150)),
                ('cidade_residencia', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=128)),
                ('is_admin', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255)),
                ('resposta', models.TextField()),
                ('ativa', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pergunta frequente',
                'verbose_name_plural': 'Perguntas frequentes',
                'ordering': ['ordem', 'pergunta'],
            },
        ),
        migrations.CreateModel(
            name='Localizacao_lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Duvida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RESPONDIDA', 'Respondida'), ('FAQ', 'Pergunta frequente')], default='PENDENTE', max_length=20)),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('respondida_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duvidas', to='app.cadastro_usuario')),
            ],
            options={
                'verbose_name': 'Dúvida',
                'verbose_name_plural': 'Dúvidas',
                'ordering': ['-enviada_em'],
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_retirada', models.DateField(blank=True, null=True)),
                ('data_devolucao_prevista', models.DateField(blank=True, null=True)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('NEGADO', 'Negado'), ('DEVOLVIDO', 'Devolvido'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='app.cadastro_materiais')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='app.cadastro_usuario')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=20)),
                ('modulo', models.CharField(max_length=100)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes', to='app.cadastro_usuario')),
            ],
            options={
                'verbose_name': 'Histórico de alteração',
                'verbose_name_plural': 'Histórico de alterações',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AddField(
            model_name='cadastro_materiais',
            name='localizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais', to='app.localizacao_lab'),
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('quantidade_visitantes', models.PositiveIntegerField(default=1)),
                ('finalidade', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('NEGADA', 'Negada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='app.cadastro_usuario')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-data', '-horario'],
            },
        ),
    ]
